import { Collection, CollectionRecord } from './types';

export const INITIAL_SYSTEM_FIELDS = [
  { name: 'id', title: 'ID', type: 'string' as const, isSystem: true },
  { name: 'createdAt', title: 'Создано', type: 'datetime' as const, isSystem: true },
  { name: 'updatedAt', title: 'Обновлено', type: 'datetime' as const, isSystem: true },
];

export const INITIAL_COLLECTIONS: Collection[] = [
  {
    name: 'support_tickets',
    title: 'Обращения и рекламации (Support)',
    description: 'Журнал рекламаций клиентов, запросов на возврат и гарантийных случаев',
    category: '🏢 Пользовательские справочники',
    icon: 'LifeBuoy',
    createdAt: '2026-03-01T10:00:00.000Z',
    updatedAt: '2026-03-20T12:00:00.000Z',
    fields: [
      { name: 'id', title: 'Код', type: 'string', isSystem: true },
      { name: 'ticket_number', title: 'Номер тикета', type: 'string', required: true },
      { name: 'client_name', title: 'Клиент', type: 'string', required: true },
      { name: 'order_number', title: 'Заказ-основание', type: 'string', required: true },
      {
        name: 'category',
        title: 'Категория',
        type: 'select',
        required: true,
        options: [
          { value: 'refund', label: 'Возврат средств', color: 'amber' },
          { value: 'defect', label: 'Брак продукции', color: 'rose' },
          { value: 'logistics', label: 'Задержка доставки', color: 'cyan' },
          { value: 'consultation', label: 'Консультация', color: 'slate' },
        ],
      },
      { name: 'amount', title: 'Сумма претензии', type: 'money', defaultValue: 0 },
      {
        name: 'priority',
        title: 'Приоритет',
        type: 'select',
        required: true,
        options: [
          { value: 'low', label: 'Низкий', color: 'slate' },
          { value: 'medium', label: 'Средний', color: 'cyan' },
          { value: 'high', label: 'Высокий', color: 'amber' },
          { value: 'critical', label: 'Критический', color: 'rose' },
        ],
      },
      {
        name: 'status',
        title: 'Статус тикета',
        type: 'status',
        required: true,
        options: [
          { value: 'new', label: 'Новый', color: 'cyan' },
          { value: 'in_progress', label: 'В расследовании', color: 'amber' },
          { value: 'resolved', label: 'Решено', color: 'emerald' },
          { value: 'rejected', label: 'Отклонено', color: 'rose' },
        ],
      },
      { name: 'contact_phone', title: 'Телефон связи', type: 'phone' },
      { name: 'description', title: 'Суть проблемы', type: 'text' },
      { name: 'is_vip', title: 'VIP-клиент', type: 'boolean', defaultValue: false },
      { name: 'createdAt', title: 'Дата создания', type: 'datetime', isSystem: true },
    ],
  },
  {
    name: 'security_audits',
    title: 'Аудит доступов & Инциденты',
    description: 'Реестр проверок информационной безопасности и мониторинга прав пользователей',
    category: '🏢 Пользовательские справочники',
    icon: 'ShieldAlert',
    createdAt: '2026-03-05T14:30:00.000Z',
    updatedAt: '2026-03-20T12:00:00.000Z',
    fields: [
      { name: 'id', title: 'ID', type: 'string', isSystem: true },
      { name: 'event_name', title: 'Событие безопасности', type: 'string', required: true },
      { name: 'operator_email', title: 'Оператор / Учетная запись', type: 'email', required: true },
      {
        name: 'service_target',
        title: 'Целевой микросервис',
        type: 'select',
        options: [
          { value: 'billing', label: 'billing-svc (Saga)', color: 'amber' },
          { value: 'orders', label: 'order-service', color: 'cyan' },
          { value: 'keycloak', label: 'auth-keycloak', color: 'purple' },
          { value: 'database', label: 'postgres-ledger', color: 'emerald' },
        ],
      },
      { name: 'ip_address', title: 'IP-адрес', type: 'string', required: true },
      {
        name: 'risk_level',
        title: 'Уровень риска',
        type: 'status',
        options: [
          { value: 'info', label: 'Информационный', color: 'slate' },
          { value: 'low', label: 'Низкий', color: 'cyan' },
          { value: 'medium', label: 'Внимание', color: 'amber' },
          { value: 'high', label: 'Угроза (High)', color: 'rose' },
        ],
      },
      { name: 'action_permitted', title: 'Действие разрешено', type: 'boolean', defaultValue: true },
      { name: 'notes', title: 'Технические детали', type: 'text' },
      { name: 'createdAt', title: 'Время фиксации', type: 'datetime', isSystem: true },
    ],
  },
];

export const INITIAL_RECORDS: Record<string, CollectionRecord[]> = {
  support_tickets: [
    {
      id: 'tick-001',
      ticket_number: 'TK-2026-041',
      client_name: 'ООО «ТехноПром»',
      order_number: '#РОМ-9402',
      category: 'refund',
      amount: 14200,
      priority: 'critical',
      status: 'in_progress',
      contact_phone: '+7 (495) 912-33-44',
      description: 'Задержка поставки партии датчиков более 5 рабочих дней. Запрошен возврат средств через Saga-процессинг.',
      is_vip: true,
      createdAt: '2026-03-19T09:15:00.000Z',
      updatedAt: '2026-03-20T11:30:00.000Z',
    },
    {
      id: 'tick-002',
      ticket_number: 'TK-2026-042',
      client_name: 'АО «СтройТорг»',
      order_number: '#РОМ-9388',
      category: 'defect',
      amount: 48900,
      priority: 'high',
      status: 'new',
      contact_phone: '+7 (812) 441-20-11',
      description: 'Повреждение упаковки контроллеров при транспортировке. Акт дефектовки составлен.',
      is_vip: false,
      createdAt: '2026-03-20T08:00:00.000Z',
      updatedAt: '2026-03-20T08:00:00.000Z',
    },
    {
      id: 'tick-003',
      ticket_number: 'TK-2026-039',
      client_name: 'ИП Смирнов А.В.',
      order_number: '#РОМ-9310',
      category: 'consultation',
      amount: 0,
      priority: 'medium',
      status: 'resolved',
      contact_phone: '+7 (903) 777-12-34',
      description: 'Запрос схемы распайки и протокола синхронизации NATS JetStream.',
      is_vip: false,
      createdAt: '2026-03-18T14:20:00.000Z',
      updatedAt: '2026-03-19T16:00:00.000Z',
    },
    {
      id: 'tick-004',
      ticket_number: 'TK-2026-038',
      client_name: 'ПАО «СеверСтальСнаб»',
      order_number: '#РОМ-9240',
      category: 'refund',
      amount: 125000,
      priority: 'high',
      status: 'resolved',
      contact_phone: '+7 (495) 555-88-99',
      description: 'Ошибочная повторная транзакция эквайринга. Успешно сторнировано и компенсировано.',
      is_vip: true,
      createdAt: '2026-03-17T11:00:00.000Z',
      updatedAt: '2026-03-18T10:15:00.000Z',
    },
  ],
  security_audits: [
    {
      id: 'sec-001',
      event_name: 'Попытка изменения лимита эквайринга без 2FA',
      operator_email: 'finance_op1@romashka.ru',
      service_target: 'billing',
      ip_address: '192.168.10.45',
      risk_level: 'high',
      action_permitted: false,
      notes: 'Сработал policy-enforcement в API Gateway. Сессия заблокирована на 15 мин.',
      createdAt: '2026-03-20T07:45:00.000Z',
      updatedAt: '2026-03-20T07:45:00.000Z',
    },
    {
      id: 'sec-002',
      event_name: 'Ротация TLS сертификата NATS JetStream кластера',
      operator_email: 'infra_robot@romashka.internal',
      service_target: 'keycloak',
      ip_address: '10.244.1.14',
      risk_level: 'info',
      action_permitted: true,
      notes: 'Автоматический выпуск cert-manager в k8s. Проверка SAN завершена успешно.',
      createdAt: '2026-03-20T04:00:00.000Z',
      updatedAt: '2026-03-20T04:00:00.000Z',
    },
    {
      id: 'sec-003',
      event_name: 'Массовый экспорт клиентской базы CRM',
      operator_email: 'sales_lead@romashka.ru',
      service_target: 'orders',
      ip_address: '192.168.12.80',
      risk_level: 'medium',
      action_permitted: true,
      notes: 'Выгрузка для квартального отчета согласована руководителем департамента.',
      createdAt: '2026-03-19T17:10:00.000Z',
      updatedAt: '2026-03-19T17:10:00.000Z',
    },
  ],
};
